import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { MaterialModule } from '../../../shared/material.module';
import { MatTableDataSource } from '@angular/material/table';
import { MatDialog } from '@angular/material/dialog';
import { DashboardCount } from '../../../core/models/dashboard.model';
import { ApplicationTableComponent } from './application-table/application-table.component';
import { forkJoin, Subscription, of } from 'rxjs';
import { finalize, filter, switchMap, catchError, take } from 'rxjs/operators';
import { UnifiedDashboardService } from '../../../core/services/unified-dashboard.service';
import { UnifiedApplication } from '../../../core/models/unified-application.model';
import { SalesmanBarmanRegistrationService } from '../../../core/services/salesman-barman-registration.service';
import { DashboardConfigService } from '../../../core/services/dashboard-config.service';
import { SidebarPendingBadgeService } from '../../../shared/services/sidebar-pending-badge.service';
import { TimerConfigService } from '../../../core/services/timer-config.service';
import { environment } from '../../../../environments/environment';
import { MyLicensesComponent } from '../my-licenses/my-licenses.component';
import Swal from 'sweetalert2';
