export enum Authority {
  SITE_ADMIN = 1,
  LICENSEE = 2,
  SINGLE_WINDOW = 3,
  DISTRICT_USER = 4,
  PERMIT_SECTION = 5,
  IT_CELL = 6,
  OFFICER_IN_CHARGE = 7,
  SUB_ENQUIRY_OFFICER = 8,
  JOINT_COMMISSIONER = 9,
  COMMISSIONER = 10,
  SECRETARY = 11,
  SUPPLY_CHAIN = 2,
}
  
