import { ComponentFixture, TestBed } from '@angular/core/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { of } from 'rxjs';

import { HologramdetailsComponent } from './hologramdetails.component';
import { HologramDataService } from '../../services/hologram-data.service';

describe('HologramdetailsComponent', () => {
  let component: HologramdetailsComponent;
  let fixture: ComponentFixture<HologramdetailsComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [HologramdetailsComponent, RouterTestingModule],
      providers: [
        {
          provide: HologramDataService,
          useValue: {
            getProcurements: () => of([]),
            performAction: () => of({}),
            notifyArrivalUpdate: () => {}
          }
        }
      ]
    })
    .compileComponents();

    fixture = TestBed.createComponent(HologramdetailsComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('auto-assigns 5 rolls of 20,000 for 1,00,000', () => {
    spyOn(window, 'alert');

    component.updateArrivalDetails({
      id: 1,
      date: '2026-04-17',
      ourRefNo: 'HQR/1101/2026-27/0001',
      fromSerial: '',
      toSerial: '',
      numberOfHolograms: 100000,
      status: 'READY',
      carton_details: [],
      supplyChainData: { localQtyLakh: 100000 }
    });

    component.currentCarton.cartoonNumber = 'A1';
    component.currentCarton.fromSerial = '1';
    component.onSerialInputChange();

    expect(component.autoGeneratedRollsPreview.length).toBe(5);
    expect(component.autoGeneratedRollsPreview[0].fromSerial).toBe('1');
    expect(component.autoGeneratedRollsPreview[0].toSerial).toBe('20000');
    expect(component.autoGeneratedRollsPreview[4].fromSerial).toBe('80001');
    expect(component.autoGeneratedRollsPreview[4].toSerial).toBe('100000');

    component.saveCurrentCarton();

    expect(component.savedCartons.length).toBe(5);
    expect(component.getSavedCartonCount()).toBe(1);
    expect(component.totalCalculatedHolograms).toBe(100000);
  });

  it('supports multiple cartons for 2,00,000', () => {
    spyOn(window, 'alert');

    component.updateArrivalDetails({
      id: 2,
      date: '2026-04-17',
      ourRefNo: 'HQR/1101/2026-27/0002',
      fromSerial: '',
      toSerial: '',
      numberOfHolograms: 200000,
      status: 'READY',
      carton_details: [],
      supplyChainData: { localQtyLakh: 200000 }
    });

    component.currentCarton.cartoonNumber = 'B1';
    component.currentCarton.fromSerial = '1';
    component.onSerialInputChange();
    component.saveCurrentCarton();

    component.currentCarton.cartoonNumber = 'B2';
    component.currentCarton.fromSerial = '200001';
    component.onSerialInputChange();
    component.saveCurrentCarton();

    expect(component.getSavedCartonCount()).toBe(2);
    expect(component.savedCartons.length).toBe(10);
    expect(component.totalCalculatedHolograms).toBe(200000);
  });
});
