export class SalesmanBarman {
  // Personal details
  id?: number;
  role!: string;
  firstName!: string;
  middleName?: string;
  lastName!: string;
  fatherHusbandName!: string;
  gender!: string;
  dob!: string;
  nationality!: string;
  address!: string;
  pan!: string;
  aadhaar!: string; // string to preserve leading zeros
  mobileNumber!: string; // string for validation
  emailId?: string;
  sikkimSubject!: boolean;

  // License details
  applicationYear!: string;
  applicationId!: string; // Generated by backend
  applicationDate!: string;
  district!: string;
  licenseCategory!: string;
  license!: string;

  // Workflow
  current_stage?: string;
  current_stage_name?: string;
  is_approved?: boolean;
  created_at?: string;
}

export class SalesmanBarmanDocuments {
  passPhoto!: File;
  aadhaarCard!: File;
  residentialCertificate!: File;
  dateofBirthProof!: File;
}