import { Component, Input, Output, EventEmitter, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatTableDataSource } from '@angular/material/table';
import { TableColumn } from '../../../../../core/models/dashboard.models';

@Component({
  selector: 'app-table-widget',
  standalone: true,
  imports: [
    CommonModule,
    MatTableModule,
    MatPaginatorModule,
    MatIconModule,
    MatButtonModule,
    MatTooltipModule
  ],
  templateUrl: './table-widget.component.html',
  styleUrls: ['./table-widget.component.scss']
})
export class TableWidgetComponent implements OnInit, OnChanges {
  @Input() data: any[] = [];
  @Input() loading = false;
  @Input() title = 'Data Table';
  @Input() subtitle?: string;
  @Input() columns: TableColumn[] = [];
  @Input() showTitle = true;
  @Input() showPagination = true;
  @Input() pageSize = 10;
  @Input() pageSizeOptions = [5, 10, 25, 50];
  @Input() maxHeight = '400px';
  @Output() refreshRequested = new EventEmitter<void>();
  @Output() exportRequested = new EventEmitter<void>();
  @Output() rowClicked = new EventEmitter<any>();

  dataSource = new MatTableDataSource<any>([]);
  displayedColumns: string[] = [];
  autoGeneratedColumns: TableColumn[] = [];

  ngOnInit() {
    this.setupTable();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['data'] || changes['columns']) {
      this.setupTable();
    }
  }

  private setupTable() {
    // Set up data source
    this.dataSource.data = this.data || [];

    // Set up columns
    if (this.columns && this.columns.length > 0) {
      // Use provided columns
      this.displayedColumns = this.columns.map(col => col.key);
    } else if (this.data && this.data.length > 0) {
      // Auto-generate columns from data
      this.autoGeneratedColumns = this.generateColumnsFromData(this.data[0]);
      this.displayedColumns = this.autoGeneratedColumns.map(col => col.key);
    } else {
      this.displayedColumns = [];
      this.autoGeneratedColumns = [];
    }
  }

  private generateColumnsFromData(firstRow: any): TableColumn[] {
    return Object.keys(firstRow).map(key => ({
      key,
      label: this.formatColumnLabel(key),
      type: this.detectColumnType(firstRow[key]),
      sortable: true,
      filterable: true
    }));
  }

  private formatColumnLabel(key: string): string {
    return key
      .replace(/([A-Z])/g, ' $1')
      .replace(/^./, str => str.toUpperCase())
      .replace(/_/g, ' ')
      .trim();
  }

  private detectColumnType(value: any): 'text' | 'number' | 'date' | 'status' | 'action' {
    if (typeof value === 'number') {
      return 'number';
    } else if (value instanceof Date || (typeof value === 'string' && !isNaN(Date.parse(value)))) {
      return 'date';
    } else if (typeof value === 'string' && ['pending', 'approved', 'rejected', 'active', 'inactive'].includes(value.toLowerCase())) {
      return 'status';
    }
    return 'text';
  }

  getColumns(): TableColumn[] {
    return this.columns.length > 0 ? this.columns : this.autoGeneratedColumns;
  }

  getColumnByKey(key: string): TableColumn | undefined {
    return this.getColumns().find(col => col.key === key);
  }

  formatCellValue(element: any, column: TableColumn): string {
    const value = element[column.key];
    
    if (value === null || value === undefined) {
      return '-';
    }

    switch (column.type) {
      case 'number':
        return typeof value === 'number' ? value.toLocaleString() : value.toString();
      
      case 'date':
        if (value instanceof Date) {
          return value.toLocaleDateString();
        } else if (typeof value === 'string') {
          const date = new Date(value);
          return isNaN(date.getTime()) ? value : date.toLocaleDateString();
        }
        return value.toString();
      
      case 'status':
        return value.toString();
      
      default:
        return value.toString();
    }
  }

  getStatusClass(value: string): string {
    const status = value.toLowerCase();
    switch (status) {
      case 'pending':
        return 'status-pending';
      case 'approved':
        return 'status-approved';
      case 'rejected':
        return 'status-rejected';
      case 'active':
        return 'status-active';
      case 'inactive':
        return 'status-inactive';
      default:
        return 'status-default';
    }
  }

  onRefresh() {
    this.refreshRequested.emit();
  }

  onExport() {
    this.exportRequested.emit();
  }

  onRowClick(row: any) {
    this.rowClicked.emit(row);
  }

  hasData(): boolean {
    return this.data && this.data.length > 0;
  }

  trackByIndex(index: number): number {
    return index;
  }
}