import { Component, ChangeDetectorRef, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HologramDataService, HologramDailyEntry, HologramIssuedEntry, HologramWastageEntry } from '../../../supplyChain/services/hologram-data.service';



@Component({
  selector: 'app-hologram-daily-register',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './hologram-daily-register.component.html',
  styleUrls: ['./hologram-daily-register.component.scss']
})
export class HologramDailyRegisterComponent implements OnInit {
  Math = Math;
  selectedMonth = 'nov'; // Current month
  selectedYear = '2025';
  selectedDate = new Date().toISOString().split('T')[0]; // Current date
  selectedHologramType: 'LOCAL' | 'EXPORT' | 'DEFENCE' = 'LOCAL';

  // Helper method to get count of editable entries
  getEditableEntriesCount(): number {
    return this.filteredEntries.filter(e => !e.isFixed).length;
  }

  // Helper method to get count of auto-generated entries
  getAutoGeneratedEntriesCount(): number {
    return this.filteredEntries.filter(e => !e.isFixed && this.isAutoGenerated(e)).length;
  }



  // Helper method to get count of saved entries
  getSavedEntriesCount(): number {
    return this.filteredEntries.filter(e => e.isFixed).length;
  }

  // Sample daily entries
  dailyEntries: HologramDailyEntry[] = [];
  approvedEntries: HologramDailyEntry[] = [];
  
  // Initialize with sample data if needed
  sampleDailyEntries: any[] = [
    {
      id: '1',
      date: '2025-07-01',
      hologramType: 'LOCAL',
      issuedFromSerial: '275346495',
      issuedToSerial: '275520000',
      issuedQuantity: 173506,
      utilizedQuantity: 173506,
      wastageFromSerial: '275455115',
      wastageToSerial: '275459428',
      wastageQuantity: 4314,
      leftOverQuantity: 0,
      damageReason: 'Machine malfunction during printing',
      isFixed: true,
      // Metadata for auto-generated entries
      referenceNo: 'HRQ/2025/001',
      brandDetails: {
        brandName: 'Sikkim Supreme Whisky',
        alcoholPercent: '42.8%',
        sizeMl: 750,
        liquorType: 'Whisky'
      },
      bottleSize: '750ml',
      submissionDate: '2025-06-30',
      usageDate: '2025-07-01',
      approvalDate: '2025-06-30',
      officerName: 'Rajesh Kumar',
      cartoonNumber: 'CTN001',
      autoGenerated: true
    },
    {
      id: '2',
      date: '2025-07-02',
      hologramType: 'LOCAL',
      issuedFromSerial: '275520001',
      issuedToSerial: '275520010',
      issuedQuantity: 10,
      utilizedQuantity: 0,
      wastageFromSerial: '',
      wastageToSerial: '',
      wastageQuantity: 0,
      leftOverQuantity: 10,
      damageReason: '',
      isFixed: false,
      // Metadata for auto-generated entries
      referenceNo: 'HRQ/2025/002',
      brandDetails: {
        brandName: 'Himalayan Gold Rum',
        alcoholPercent: '40%',
        sizeMl: 750,
        liquorType: 'Rum'
      },
      bottleSize: '750ml',
      submissionDate: '2025-07-01',
      usageDate: '2025-07-02',
      approvalDate: '2025-07-01',
      officerName: 'Rajesh Kumar',
      cartoonNumber: 'CTN002',
      autoGenerated: true
    }
  ];

  filteredEntries: HologramDailyEntry[] = [];
  previousMonthBalance = 249899;

  // Pagination
  pageSize = 10;
  currentPage = 1;

  constructor(
    private router: Router, 
    private cdr: ChangeDetectorRef,
    private hologramDataService: HologramDataService
  ) {
    console.log('HologramDailyRegisterComponent constructor called');
    
    // Initialize with current date/month/year
    const now = new Date();
    this.selectedDate = now.toISOString().split('T')[0];
    this.selectedMonth = now.toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    this.selectedYear = now.getFullYear().toString();
    
    // Load approved hologram entries from officer approvals
    this.loadApprovedEntries();
    
    // Load existing data from service
    const existingEntries = this.hologramDataService.getDailyEntries();
    
    // If no approved entries and no existing entries, load sample data
    if (this.approvedEntries.length === 0 && existingEntries.length === 0) {
      this.initializeSampleData();
    } else {
      // Merge approved entries with existing entries
      this.mergeApprovedEntries(existingEntries);
    }
    
    // Migrate legacy entries and calculate quantities for all entries
    this.dailyEntries.forEach(entry => {
      // Migrate legacy entries to new structure
      const migratedEntry = this.hologramDataService.migrateLegacyEntry(entry);
      Object.assign(entry, migratedEntry);
      
      // Store original hologram quantity if not already stored
      if (!(entry as any).originalHologramQty) {
        (entry as any).originalHologramQty = entry.utilizedQuantity || entry.issuedQuantity || 0;
      }
      
      // Initialize arrays if needed
      this.initializeEntryArrays(entry);
      
      // Calculate quantities
      this.calculateTotalQuantities(entry);
    });
    
    this.loadFilteredData();
    
    console.log('Constructor completed. Daily entries:', this.dailyEntries.length);
    console.log('Filtered entries:', this.filteredEntries.length);
  }

  ngOnInit(): void {
    // Ensure data is properly loaded and service is updated
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    console.log('ngOnInit: Service updated with current entries');
    
    // Listen for storage changes to auto-refresh when new approvals come in
    window.addEventListener('storage', (e) => {
      if (e.key === 'approvedHologramEntries') {
        console.log('New approved entries detected, refreshing...');
        this.loadApprovedEntries();
        this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
        this.loadFilteredData();
        this.cdr.detectChanges();
      }
    });
    
    // Check for updates every 30 seconds
    setInterval(() => {
      this.loadApprovedEntries();
      this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
      this.loadFilteredData();
    }, 30000);
  }

  loadFilteredData(): void {
    const monthNumber = this.getMonthNumber(this.selectedMonth);
    const datePrefix = `${this.selectedYear}-${monthNumber}`;
    
    console.log('Filtering data with:', {
      selectedType: this.selectedHologramType,
      selectedDate: this.selectedDate,
      datePrefix: datePrefix,
      totalEntries: this.dailyEntries.length
    });
    
    this.filteredEntries = this.dailyEntries.filter(entry => {
      const typeMatch = entry.hologramType === this.selectedHologramType;
      
      // If specific date is selected, filter by exact date
      // Otherwise, filter by month/year
      let dateMatch = false;
      if (this.selectedDate) {
        dateMatch = entry.date === this.selectedDate;
      } else {
        dateMatch = entry.date.startsWith(datePrefix);
      }
      
      console.log(`Entry ${entry.id}: type=${entry.hologramType} (${typeMatch}), date=${entry.date} (${dateMatch}), isFixed=${entry.isFixed}`);
      
      return typeMatch && dateMatch;
    });
    
    console.log('Filtered result:', this.filteredEntries.length, 'entries');
    
    // Initialize entry arrays for new structure
    this.filteredEntries.forEach(entry => {
      this.initializeEntryArrays(entry);
    });
  }

  getMonthNumber(month: string): string {
    const months: { [key: string]: string } = {
      'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04',
      'may': '05', 'jun': '06', 'jul': '07', 'aug': '08',
      'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12'
    };
    return months[month] || '01';
  }

  onMonthYearChange(): void {
    this.loadFilteredData();
    this.currentPage = 1;
  }

  onDateFilterChange(): void {
    this.loadFilteredData();
    this.currentPage = 1;
  }

  onHologramTypeChange(type: 'LOCAL' | 'EXPORT' | 'DEFENCE'): void {
    this.selectedHologramType = type;
    this.loadFilteredData();
    this.currentPage = 1;
  }

  hasActiveFilters(): boolean {
    const today = new Date().toISOString().split('T')[0];
    const currentMonth = new Date().toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    const currentYear = new Date().getFullYear().toString();
    
    return this.selectedDate !== today || 
           this.selectedMonth !== currentMonth || 
           this.selectedYear !== currentYear;
  }

  clearAllFilters(): void {
    // Reset to current date/month/year
    this.selectedDate = new Date().toISOString().split('T')[0];
    this.selectedMonth = new Date().toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    this.selectedYear = new Date().getFullYear().toString();
    
    this.loadFilteredData();
    this.currentPage = 1;
  }

  getCurrentHologramTypeDisplay(): string {
    const monthNames: { [key: string]: string } = {
      'jan': 'January', 'feb': 'February', 'mar': 'March', 'apr': 'April',
      'may': 'May', 'jun': 'June', 'jul': 'July', 'aug': 'August',
      'sep': 'September', 'oct': 'October', 'nov': 'November', 'dec': 'December'
    };
    return `${monthNames[this.selectedMonth]} ${this.selectedYear} - ${this.selectedHologramType}`;
  }

  private initializeSampleData(): void {
    // Only initialize sample data if no approved entries exist
    if (this.approvedEntries.length === 0 && this.dailyEntries.length === 0) {
      this.dailyEntries = this.sampleDailyEntries.slice(); // Copy sample data
      this.hologramDataService.updateDailyEntries(this.dailyEntries);
      console.log('Initialized with sample data:', this.dailyEntries);
    }
  }



  onEntryDataChange(entry: HologramDailyEntry): void {
    const issuedQty = this.calculateQuantityFromSerials(entry.issuedFromSerial || '', entry.issuedToSerial || '');
    const wastageQty = this.calculateQuantityFromSerials(entry.wastageFromSerial || '', entry.wastageToSerial || '');
    
    entry.issuedQuantity = issuedQty;
    entry.wastageQuantity = wastageQty;
    
    // Get original hologram quantity (stored when entry is created)
    const originalHologramQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
    
    // Calculate left over: Original Hologram Qty - (Issued Qty + Wastage Qty)
    const totalUsed = issuedQty + wastageQty;
    entry.leftOverQuantity = originalHologramQty - totalUsed;
    
    // Utilized quantity equals issued quantity
    entry.utilizedQuantity = issuedQty;
    
    // Update the service with the changed data immediately
    this.hologramDataService.updateDailyEntry(entry);
    console.log('Daily register updated entry in service:', entry.id, entry);
    
    // Force change detection to update summary
    this.cdr.detectChanges();
  }

  onSerialChange(entry: HologramDailyEntry): void {
    // Recalculate quantities when serials change
    this.onEntryDataChange(entry);
    this.cdr.detectChanges();
  }

  private calculateQuantityFromSerials(fromSerial: string, toSerial: string): number {
    return this.hologramDataService.calculateQuantityFromSerials(fromSerial, toSerial);
  }

  saveEntry(entry: HologramDailyEntry): void {
    // Validate required fields
    if (!entry.date) {
      alert('Please enter a date before saving');
      return;
    }
    
    if (!entry.issuedFromSerial || !entry.issuedToSerial) {
      alert('Please enter both Issued From Serial and Issued To Serial numbers');
      return;
    }
    
    // Calculate final quantities before saving
    this.onEntryDataChange(entry);
    
    // Validate that issued quantity is calculated
    if (!entry.issuedQuantity || entry.issuedQuantity <= 0) {
      alert('Please enter valid serial numbers to calculate issued quantity');
      return;
    }
    
    // Mark as fixed (saved)
    entry.isFixed = true;
    
    // Update the service with all entries
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    console.log('Daily register updated all entries in service:', this.dailyEntries.length, 'entries');
    
    // Refresh the display and summary
    this.loadFilteredData();
    
    // Force change detection to update summary
    this.cdr.detectChanges();
    
    // Show success message
    alert('Entry saved successfully! Monthly statement will be automatically updated.');
    
    console.log('Entry saved successfully:', entry);
  }



  openMonthlyStatement(): void {
    // Navigate to monthly report with current filters
    this.router.navigate(['/dev-hologram-monthly-report'], {
      queryParams: {
        month: this.selectedMonth,
        year: this.selectedYear,
        type: this.selectedHologramType
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/dev-supply-chain']);
  }

  // Calculate totals for monthly register auto-calculation
  calculateMonthlyTotals(): {
    totalIssued: number;
    totalUtilized: number;
    totalWastage: number;
    totalLeftOver: number;
    utilizationFromSerial: string;
    utilizationToSerial: string;
    wastageFromSerial: string;
    wastageToSerial: string;
  } {
    // Always recalculate from current filtered entries
    const monthEntries = this.filteredEntries.filter(entry => entry.isFixed);
    
    let totalIssued = 0;
    let totalUtilized = 0;
    let totalWastage = 0;
    let totalLeftOver = 0;
    
    let utilizationFromSerial = '';
    let utilizationToSerial = '';
    let wastageFromSerial = '';
    let wastageToSerial = '';

    if (monthEntries.length > 0) {
      // Sort entries by date to get correct first and last serials
      const sortedEntries = monthEntries.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
      
      // Find first and last utilization serials
      const utilizationEntries = sortedEntries.filter(e => e.utilizedQuantity > 0 && e.issuedFromSerial && e.issuedToSerial);
      if (utilizationEntries.length > 0) {
        utilizationFromSerial = utilizationEntries[0].issuedFromSerial || '';
        utilizationToSerial = utilizationEntries[utilizationEntries.length - 1].issuedToSerial || '';
      }

      // Find first and last wastage serials
      const wastageEntries = sortedEntries.filter(e => (e.wastageQuantity || 0) > 0 && e.wastageFromSerial && e.wastageToSerial);
      if (wastageEntries.length > 0) {
        wastageFromSerial = wastageEntries[0].wastageFromSerial || '';
        wastageToSerial = wastageEntries[wastageEntries.length - 1].wastageToSerial || '';
      }

      // Calculate totals
      totalIssued = sortedEntries.reduce((sum, entry) => sum + (entry.issuedQuantity || 0), 0);
      totalUtilized = sortedEntries.reduce((sum, entry) => sum + entry.utilizedQuantity, 0);
      totalWastage = sortedEntries.reduce((sum, entry) => sum + (entry.wastageQuantity || 0), 0);
      totalLeftOver = sortedEntries.reduce((sum, entry) => sum + entry.leftOverQuantity, 0);
    }

    // Update the service with latest totals
    this.hologramDataService.updateDailyEntries(this.dailyEntries);

    return {
      totalIssued,
      totalUtilized,
      totalWastage,
      totalLeftOver,
      utilizationFromSerial,
      utilizationToSerial,
      wastageFromSerial,
      wastageToSerial
    };
  }

  // Force refresh summary
  refreshSummary(): void {
    this.loadFilteredData();
    this.cdr.detectChanges();
  }

  // Get current timestamp for display
  getCurrentTimestamp(): string {
    return new Date().toLocaleString();
  }

  // Check if there are any fixed entries for live data indicator
  hasFixedEntries(): boolean {
    return this.filteredEntries.filter(e => e.isFixed).length > 0;
  }

  // Calculate issued quantity from serials
  calculateIssuedQuantity(entry: HologramDailyEntry): number {
    return this.calculateQuantityFromSerials(entry.issuedFromSerial || '', entry.issuedToSerial || '');
  }

  // Calculate wastage quantity from serials
  calculateWastageQuantity(entry: HologramDailyEntry): number {
    return this.calculateQuantityFromSerials(entry.wastageFromSerial || '', entry.wastageToSerial || '');
  }



  // Load approved hologram entries from officer approvals
  loadApprovedEntries(): void {
    const approvedEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    console.log('Loading approved entries from localStorage:', approvedEntries.length);
    
    // Convert approved entries to daily entry format
    this.approvedEntries = approvedEntries.map((entry: any) => {
      const originalQty = entry.issuedQuantity || entry.utilizedQuantity || 0;
      return {
        id: entry.id,
        date: entry.date,
        hologramType: entry.hologramType,
        issuedFromSerial: entry.issuedFromSerial || '',
        issuedToSerial: entry.issuedToSerial || '',
        issuedQuantity: 0, // Will be calculated from serials
        utilizedQuantity: originalQty,
        wastageFromSerial: entry.wastageFromSerial || '',
        wastageToSerial: entry.wastageToSerial || '',
        wastageQuantity: 0, // Will be calculated from serials
        leftOverQuantity: originalQty, // Will be recalculated
        damageReason: entry.damageReason || '',
        isFixed: entry.isFixed || false,
        // Store original hologram quantity for calculation
        originalHologramQty: originalQty,
        // Additional metadata for display
        referenceNo: entry.referenceNo,
        brandDetails: entry.brandDetails,
        bottleSize: entry.bottleSize,
        submissionDate: entry.submissionDate,
        usageDate: entry.usageDate,
        approvalDate: entry.approvalDate,
        officerName: entry.officerName,
        cartoonNumber: entry.cartoonNumber,
        autoGenerated: entry.autoGenerated || false
      };
    });
  }

  // Merge approved entries with existing entries
  mergeApprovedEntries(existingEntries: HologramDailyEntry[]): void {
    // Get IDs of existing entries to avoid duplicates
    const existingIds = new Set(existingEntries.map(entry => entry.id));
    
    // Filter out approved entries that already exist
    const newApprovedEntries = this.approvedEntries.filter(entry => !existingIds.has(entry.id));
    
    // Combine all entries
    this.dailyEntries = [...existingEntries, ...newApprovedEntries];
    
    // Update the service with merged data
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    
    console.log('Merged entries:', {
      existing: existingEntries.length,
      newApproved: newApprovedEntries.length,
      total: this.dailyEntries.length
    });
  }

  // Check if entry is auto-generated from approval
  isAutoGenerated(entry: HologramDailyEntry): boolean {
    return (entry as any).autoGenerated === true;
  }

  // Get entry metadata for display
  getEntryMetadata(entry: HologramDailyEntry): any {
    console.log('Entry metadata:', entry);
    return {
      referenceNo: (entry as any).referenceNo || 'Manual Entry',
      brandDetails: (entry as any).brandDetails || { brandName: 'Sample Brand' },
      bottleSize: (entry as any).bottleSize || '750ml',
      submissionDate: (entry as any).submissionDate || entry.date,
      usageDate: (entry as any).usageDate || entry.date,
      approvalDate: (entry as any).approvalDate || entry.date,
      officerName: (entry as any).officerName || 'System',
      cartoonNumber: (entry as any).cartoonNumber || 'CTN001'
    };
  }

  // Manual refresh method
  refreshEntries(): void {
    console.log('Manually refreshing entries...');
    this.loadApprovedEntries();
    this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
    this.loadFilteredData();
    this.cdr.detectChanges();
    
    const newCount = this.getAutoGeneratedEntriesCount();
    alert(`Entries refreshed! Found ${newCount} auto-generated entries from officer approvals.`);
  }

  // Test method to simulate officer approval
  simulateOfficerApproval(): void {
    const testApprovalEntry = {
      id: `AUTO_${Date.now()}_TEST`,
      date: new Date().toISOString().split('T')[0],
      hologramType: this.selectedHologramType,
      issuedFromSerial: 'HG275346495',
      issuedToSerial: 'HG275347495',
      issuedQuantity: 1000,
      utilizedQuantity: 0,
      wastageFromSerial: '',
      wastageToSerial: '',
      wastageQuantity: 0,
      leftOverQuantity: 1000,
      damageReason: '',
      isFixed: false,
      // Additional metadata for tracking
      referenceNo: `HRQ/${new Date().getFullYear()}/${String(Date.now()).slice(-6)}`,
      brandDetails: {
        brandName: 'Sikkim Supreme Whisky',
        alcoholPercent: '42.8%',
        sizeMl: 750,
        liquorType: 'Whisky'
      },
      bottleSize: '750ml',
      submissionDate: new Date().toISOString().split('T')[0],
      usageDate: new Date().toISOString().split('T')[0],
      approvalDate: new Date().toISOString().split('T')[0],
      officerName: 'Test Officer',
      cartoonNumber: 'CTN001',
      autoGenerated: true
    };

    // Save to localStorage
    const existingEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    existingEntries.push(testApprovalEntry);
    localStorage.setItem('approvedHologramEntries', JSON.stringify(existingEntries));

    // Refresh the display
    this.refreshEntries();
    
    alert('Test officer approval simulated! A new auto-generated entry has been created.');
  }

  // Debug method to check localStorage contents
  debugLocalStorage(): void {
    const approvedEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    const hologramRequests = JSON.parse(localStorage.getItem('hologramRequests') || '[]');
    const hologramApplications = JSON.parse(localStorage.getItem('hologramApplications') || '[]');
    
    console.log('=== LOCALSTORAGE DEBUG ===');
    console.log('approvedHologramEntries:', approvedEntries);
    console.log('hologramRequests:', hologramRequests);
    console.log('hologramApplications:', hologramApplications);
    console.log('Current dailyEntries:', this.dailyEntries);
    console.log('Current filteredEntries:', this.filteredEntries);
    console.log('Current approvedEntries:', this.approvedEntries);
    
    const message = `
LocalStorage Debug:
- approvedHologramEntries: ${approvedEntries.length} items
- hologramRequests: ${hologramRequests.length} items  
- hologramApplications: ${hologramApplications.length} items
- Current dailyEntries: ${this.dailyEntries.length} items
- Current filteredEntries: ${this.filteredEntries.length} items
- Current approvedEntries: ${this.approvedEntries.length} items

Check browser console for detailed data.
    `;
    
    alert(message);
  }

  // Pagination methods
  getTotalPages(): number {
    return Math.ceil(this.filteredEntries.length / this.pageSize);
  }

  getPagedEntries(): HologramDailyEntry[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredEntries.slice(start, start + this.pageSize);
  }

  goToPage(page: number): void {
    const totalPages = this.getTotalPages();
    if (page >= 1 && page <= totalPages) {
      this.currentPage = page;
    }
  }

  changePageSize(size: number): void {
    this.pageSize = size;
    this.currentPage = 1;
  }

  // Methods for managing multiple issued entries
  addIssuedEntry(entry: HologramDailyEntry): void {
    if (!entry.issuedEntries) {
      entry.issuedEntries = [];
    }
    
    const newIssuedEntry: HologramIssuedEntry = {
      id: this.hologramDataService.generateId(),
      fromSerial: '',
      toSerial: '',
      quantity: 0
    };
    
    entry.issuedEntries.push(newIssuedEntry);
    this.calculateTotalQuantities(entry);
  }

  removeIssuedEntry(entry: HologramDailyEntry, index: number): void {
    if (entry.issuedEntries && entry.issuedEntries.length > 1) {
      entry.issuedEntries.splice(index, 1);
      this.calculateTotalQuantities(entry);
    }
  }

  onIssuedSerialChange(entry: HologramDailyEntry, issuedEntry: HologramIssuedEntry): void {
    issuedEntry.quantity = this.calculateQuantityFromSerials(issuedEntry.fromSerial, issuedEntry.toSerial);
    this.calculateTotalQuantities(entry);
  }

  // Methods for managing multiple wastage entries
  addWastageEntry(entry: HologramDailyEntry): void {
    if (!entry.wastageEntries) {
      entry.wastageEntries = [];
    }
    
    const newWastageEntry: HologramWastageEntry = {
      id: this.hologramDataService.generateId(),
      fromSerial: '',
      toSerial: '',
      quantity: 0,
      damageReason: ''
    };
    
    entry.wastageEntries.push(newWastageEntry);
    this.calculateTotalQuantities(entry);
  }

  removeWastageEntry(entry: HologramDailyEntry, index: number): void {
    if (entry.wastageEntries && entry.wastageEntries.length > 1) {
      entry.wastageEntries.splice(index, 1);
      this.calculateTotalQuantities(entry);
    }
  }

  onWastageSerialChange(entry: HologramDailyEntry, wastageEntry: HologramWastageEntry): void {
    wastageEntry.quantity = this.calculateQuantityFromSerials(wastageEntry.fromSerial, wastageEntry.toSerial);
    this.calculateTotalQuantities(entry);
  }

  // Calculate total quantities from all issued and wastage entries
  calculateTotalQuantities(entry: HologramDailyEntry): void {
    // Calculate total issued quantity
    const totalIssued = (entry.issuedEntries || []).reduce((sum, issued) => sum + (issued.quantity || 0), 0);
    
    // Calculate total wastage quantity
    const totalWastage = (entry.wastageEntries || []).reduce((sum, wastage) => sum + (wastage.quantity || 0), 0);
    
    // Update legacy fields for backward compatibility
    entry.issuedQuantity = totalIssued;
    entry.wastageQuantity = totalWastage;
    
    // Get original hologram quantity
    const originalHologramQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
    
    // Calculate left over: Original Hologram Qty - (Issued Qty + Wastage Qty)
    const totalUsed = totalIssued + totalWastage;
    entry.leftOverQuantity = originalHologramQty - totalUsed;
  }

  // Get total issued quantity for display
  getTotalIssuedQuantity(entry: HologramDailyEntry): number {
    return this.hologramDataService.getTotalIssuedQuantity(entry);
  }

  // Get total wastage quantity for display
  getTotalWastageQuantity(entry: HologramDailyEntry): number {
    return this.hologramDataService.getTotalWastageQuantity(entry);
  }

  // Initialize entries with at least one issued and wastage entry
  initializeEntryArrays(entry: HologramDailyEntry): void {
    if (!entry.issuedEntries || entry.issuedEntries.length === 0) {
      entry.issuedEntries = [{
        id: this.hologramDataService.generateId(),
        fromSerial: entry.issuedFromSerial || '',
        toSerial: entry.issuedToSerial || '',
        quantity: entry.issuedQuantity || 0
      }];
    }
    
    if (!entry.wastageEntries || entry.wastageEntries.length === 0) {
      entry.wastageEntries = [{
        id: this.hologramDataService.generateId(),
        fromSerial: entry.wastageFromSerial || '',
        toSerial: entry.wastageToSerial || '',
        quantity: entry.wastageQuantity || 0,
        damageReason: entry.damageReason || ''
      }];
    }
  }
}