import { Component, ChangeDetectorRef, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { HologramDataService, HologramDailyEntry, HologramIssuedEntry, HologramWastageEntry } from '../../../supplyChain/services/hologram-data.service';



@Component({
  selector: 'app-hologram-daily-register',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './hologram-daily-register.component.html',
  styleUrls: ['./hologram-daily-register.component.scss']
})
export class HologramDailyRegisterComponent implements OnInit {
  Math = Math;
  selectedMonth = 'nov'; // Current month
  selectedYear = '2025';
  selectedDate = new Date().toISOString().split('T')[0]; // Current date
  selectedHologramType: 'LOCAL' | 'EXPORT' | 'DEFENCE' = 'LOCAL';
  entryToSave: HologramDailyEntry | null = null; // Store entry for modal

  // Helper method to get count of editable entries
  getEditableEntriesCount(): number {
    return this.filteredEntries.filter(e => !e.isFixed).length;
  }

  // Helper method to get count of auto-generated entries
  getAutoGeneratedEntriesCount(): number {
    return this.filteredEntries.filter(e => !e.isFixed && this.isAutoGenerated(e)).length;
  }



  // Helper method to get count of saved entries
  getSavedEntriesCount(): number {
    return this.filteredEntries.filter(e => e.isFixed).length;
  }

  // Sample daily entries
  dailyEntries: HologramDailyEntry[] = [];
  approvedEntries: HologramDailyEntry[] = [];
  
  // Initialize with sample data if needed
  sampleDailyEntries: any[] = [
    {
      id: '1',
      date: '2025-07-01',
      hologramType: 'LOCAL',
      issuedFromSerial: '275346495',
      issuedToSerial: '275520000',
      issuedQuantity: 173506,
      utilizedQuantity: 173506,
      wastageFromSerial: '275455115',
      wastageToSerial: '275459428',
      wastageQuantity: 4314,
      leftOverQuantity: 0,
      damageReason: 'Machine malfunction during printing',
      isFixed: true,
      // Metadata for auto-generated entries
      referenceNo: 'HRQ/2025/001',
      brandDetails: {
        brandName: 'Sikkim Supreme Whisky',
        alcoholPercent: '42.8%',
        sizeMl: 750,
        liquorType: 'Whisky'
      },
      bottleSize: '750ml',
      submissionDate: '2025-06-30',
      usageDate: '2025-07-01',
      approvalDate: '2025-06-30',
      officerName: 'Rajesh Kumar',
      cartoonNumber: 'CTN001',
      autoGenerated: true
    },
    {
      id: '2',
      date: '2025-07-02',
      hologramType: 'LOCAL',
      issuedFromSerial: '275520001',
      issuedToSerial: '275520010',
      issuedQuantity: 10,
      utilizedQuantity: 0,
      wastageFromSerial: '',
      wastageToSerial: '',
      wastageQuantity: 0,
      leftOverQuantity: 10,
      damageReason: '',
      isFixed: false,
      // Metadata for auto-generated entries
      referenceNo: 'HRQ/2025/002',
      brandDetails: {
        brandName: 'Himalayan Gold Rum',
        alcoholPercent: '40%',
        sizeMl: 750,
        liquorType: 'Rum'
      },
      bottleSize: '750ml',
      submissionDate: '2025-07-01',
      usageDate: '2025-07-02',
      approvalDate: '2025-07-01',
      officerName: 'Rajesh Kumar',
      cartoonNumber: 'CTN002',
      autoGenerated: true
    }
  ];

  filteredEntries: HologramDailyEntry[] = [];
  previousMonthBalance = 249899;

  // Pagination
  pageSize = 10;
  currentPage = 1;

  constructor(
    private router: Router, 
    private cdr: ChangeDetectorRef,
    private hologramDataService: HologramDataService
  ) {
    console.log('HologramDailyRegisterComponent constructor called');
    
    // Initialize with current date/month/year
    const now = new Date();
    this.selectedDate = now.toISOString().split('T')[0];
    this.selectedMonth = now.toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    this.selectedYear = now.getFullYear().toString();
    
    // Load approved hologram entries from officer approvals
    this.loadApprovedEntries();
    
    // Load existing data from service
    const existingEntries = this.hologramDataService.getDailyEntries();
    
    // If no approved entries and no existing entries, load sample data
    if (this.approvedEntries.length === 0 && existingEntries.length === 0) {
      this.initializeSampleData();
    } else {
      // Merge approved entries with existing entries
      this.mergeApprovedEntries(existingEntries);
    }
    
    // Migrate legacy entries and calculate quantities for all entries
    this.dailyEntries.forEach(entry => {
      // Migrate legacy entries to new structure
      const migratedEntry = this.hologramDataService.migrateLegacyEntry(entry);
      Object.assign(entry, migratedEntry);
      
      // Store original hologram quantity if not already stored
      if (!(entry as any).originalHologramQty) {
        (entry as any).originalHologramQty = entry.utilizedQuantity || entry.issuedQuantity || 0;
      }
      
      // Initialize arrays if needed
      this.initializeEntryArrays(entry);
      
      // Calculate quantities
      this.calculateTotalQuantities(entry);
    });
    
    this.loadFilteredData();
    
    console.log('Constructor completed. Daily entries:', this.dailyEntries.length);
    console.log('Filtered entries:', this.filteredEntries.length);
  }

  ngOnInit(): void {
    // Ensure data is properly loaded and service is updated
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    console.log('ngOnInit: Service updated with current entries');
    
    // Listen for storage changes to auto-refresh when new approvals come in
    window.addEventListener('storage', (e) => {
      if (e.key === 'approvedHologramEntries') {
        console.log('New approved entries detected, refreshing...');
        this.loadApprovedEntries();
        this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
        this.loadFilteredData();
        this.cdr.detectChanges();
      }
    });
    
    // Check for updates every 30 seconds
    setInterval(() => {
      this.loadApprovedEntries();
      this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
      this.loadFilteredData();
    }, 30000);
  }

  loadFilteredData(): void {
    const monthNumber = this.getMonthNumber(this.selectedMonth);
    const datePrefix = `${this.selectedYear}-${monthNumber}`;
    
    console.log('Filtering data with:', {
      selectedType: this.selectedHologramType,
      selectedDate: this.selectedDate,
      datePrefix: datePrefix,
      totalEntries: this.dailyEntries.length
    });
    
    this.filteredEntries = this.dailyEntries.filter(entry => {
      const typeMatch = entry.hologramType === this.selectedHologramType;
      
      // If specific date is selected, filter by exact date
      // Otherwise, filter by month/year
      let dateMatch = false;
      if (this.selectedDate) {
        dateMatch = entry.date === this.selectedDate;
      } else {
        dateMatch = entry.date.startsWith(datePrefix);
      }
      
      console.log(`Entry ${entry.id}: type=${entry.hologramType} (${typeMatch}), date=${entry.date} (${dateMatch}), isFixed=${entry.isFixed}`);
      
      return typeMatch && dateMatch;
    });
    
    console.log('Filtered result:', this.filteredEntries.length, 'entries');
    
    // Initialize entry arrays for new structure (only for non-fixed entries)
    this.filteredEntries.forEach(entry => {
      // Only initialize arrays for entries that haven't been saved yet
      // Fixed entries should not be modified
      if (!entry.isFixed) {
        this.initializeEntryArrays(entry);
      }
    });
  }

  getMonthNumber(month: string): string {
    const months: { [key: string]: string } = {
      'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04',
      'may': '05', 'jun': '06', 'jul': '07', 'aug': '08',
      'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12'
    };
    return months[month] || '01';
  }

  onMonthYearChange(): void {
    this.loadFilteredData();
    this.currentPage = 1;
  }

  onDateFilterChange(): void {
    this.loadFilteredData();
    this.currentPage = 1;
  }

  onHologramTypeChange(type: 'LOCAL' | 'EXPORT' | 'DEFENCE'): void {
    this.selectedHologramType = type;
    this.loadFilteredData();
    this.currentPage = 1;
  }

  hasActiveFilters(): boolean {
    const today = new Date().toISOString().split('T')[0];
    const currentMonth = new Date().toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    const currentYear = new Date().getFullYear().toString();
    
    return this.selectedDate !== today || 
           this.selectedMonth !== currentMonth || 
           this.selectedYear !== currentYear;
  }

  clearAllFilters(): void {
    // Reset to current date/month/year
    this.selectedDate = new Date().toISOString().split('T')[0];
    this.selectedMonth = new Date().toLocaleDateString('en-US', { month: 'short' }).toLowerCase();
    this.selectedYear = new Date().getFullYear().toString();
    
    this.loadFilteredData();
    this.currentPage = 1;
  }

  getCurrentHologramTypeDisplay(): string {
    const monthNames: { [key: string]: string } = {
      'jan': 'January', 'feb': 'February', 'mar': 'March', 'apr': 'April',
      'may': 'May', 'jun': 'June', 'jul': 'July', 'aug': 'August',
      'sep': 'September', 'oct': 'October', 'nov': 'November', 'dec': 'December'
    };
    return `${monthNames[this.selectedMonth]} ${this.selectedYear} - ${this.selectedHologramType}`;
  }

  private initializeSampleData(): void {
    // Only initialize sample data if no approved entries exist
    if (this.approvedEntries.length === 0 && this.dailyEntries.length === 0) {
      this.dailyEntries = this.sampleDailyEntries.slice(); // Copy sample data
      this.hologramDataService.updateDailyEntries(this.dailyEntries);
      console.log('Initialized with sample data:', this.dailyEntries);
    }
  }



  onEntryDataChange(entry: HologramDailyEntry): void {
    // IMPORTANT: Do NOT recalculate for fixed (saved) entries
    if (entry.isFixed) {
      console.log('Skipping data change for fixed entry:', entry.id);
      return;
    }
    
    const issuedQty = this.calculateQuantityFromSerials(entry.issuedFromSerial || '', entry.issuedToSerial || '');
    const wastageQty = this.calculateQuantityFromSerials(entry.wastageFromSerial || '', entry.wastageToSerial || '');
    
    entry.issuedQuantity = issuedQty;
    entry.wastageQuantity = wastageQty;
    
    // Get original hologram quantity (stored when entry is created)
    // IMPORTANT: Do NOT modify utilizedQuantity - it should remain constant
    const originalHologramQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
    
    // Store original hologram qty if not already stored
    if (!(entry as any).originalHologramQty) {
      (entry as any).originalHologramQty = entry.utilizedQuantity;
    }
    
    // Calculate left over: Original Hologram Qty - (Issued Qty + Wastage Qty)
    const totalUsed = issuedQty + wastageQty;
    entry.leftOverQuantity = originalHologramQty - totalUsed;
    
    // Calculate total: Issued + Wastage + Left Over
    const totalCalculation = issuedQty + wastageQty + entry.leftOverQuantity;
    
    // Validate that total calculation matches hologram quantity
    // Error only if total EXCEEDS hologram quantity
    if (totalCalculation > originalHologramQty) {
      const excess = totalCalculation - originalHologramQty;
      (entry as any).hasValidationError = true;
      (entry as any).validationMessage = `Total (${totalCalculation.toLocaleString()}) exceeds hologram quantity (${originalHologramQty.toLocaleString()}) by ${excess.toLocaleString()} units.`;
    } else {
      (entry as any).hasValidationError = false;
      (entry as any).validationMessage = '';
    }
    
    // DO NOT modify utilizedQuantity here - it should remain the original hologram quantity
    
    // DO NOT auto-save - only save when user clicks "Save Entry" button
    // this.hologramDataService.updateDailyEntry(entry);
    // console.log('Daily register updated entry in service:', entry.id, entry);
    
    // Force change detection to update summary
    this.cdr.detectChanges();
  }

  onSerialChange(entry: HologramDailyEntry): void {
    // Recalculate quantities when serials change
    this.onEntryDataChange(entry);
    this.cdr.detectChanges();
  }

  private calculateQuantityFromSerials(fromSerial: string, toSerial: string): number {
    return this.hologramDataService.calculateQuantityFromSerials(fromSerial, toSerial);
  }

  saveEntry(entry: HologramDailyEntry): void {
    // Validate required fields
    if (!entry.date) {
      alert('Please enter a date before saving');
      return;
    }
    
    // Check if there are any issued entries with serials
    const hasIssuedEntries = entry.issuedEntries && entry.issuedEntries.length > 0 && 
                             entry.issuedEntries.some(e => e.fromSerial && e.toSerial);
    
    if (!hasIssuedEntries) {
      alert('Please enter at least one Issued From Serial and Issued To Serial');
      return;
    }
    
    // DO NOT recalculate here - quantities should already be calculated from serial changes
    // Just ensure total quantities are up to date
    this.calculateTotalQuantities(entry);
    
    // Validate that issued quantity is calculated
    if (!entry.issuedQuantity || entry.issuedQuantity <= 0) {
      alert('Please enter valid serial numbers to calculate issued quantity');
      return;
    }
    
    // Store entry for modal
    this.entryToSave = entry;
    
    // Show the modal
    const modalElement = document.getElementById('saveConfirmationModal');
    if (modalElement) {
      const modal = new (window as any).bootstrap.Modal(modalElement);
      modal.show();
    }
  }

  confirmSave(): void {
    if (!this.entryToSave) return;
    
    const entry = this.entryToSave;
    
    // IMPORTANT: Store the current leftover quantity before marking as fixed
    // This prevents recalculation from changing the leftover value
    const savedLeftOver = entry.leftOverQuantity;
    const savedIssuedQty = entry.issuedQuantity;
    const savedWastageQty = entry.wastageQuantity;
    
    // Mark as fixed (saved)
    entry.isFixed = true;
    
    // Restore the exact quantities that were calculated before save
    // This prevents any recalculation from changing the values
    entry.leftOverQuantity = savedLeftOver;
    entry.issuedQuantity = savedIssuedQty;
    entry.wastageQuantity = savedWastageQty;
    
    // Clear validation flags
    (entry as any).hasValidationError = false;
    (entry as any).validationMessage = '';
    
    // Add timestamp for when entry was saved
    (entry as any).savedAt = new Date().toISOString();
    (entry as any).savedBy = 'Supply Chain User';
    
    // Mark as pending approval for Officer in Charge
    (entry as any).approvalStatus = 'PENDING';
    
    // Save to localStorage for Officer in Charge verification
    this.saveEntryForOfficerVerification(entry);
    
    // DO NOT update roll data here - wait for Officer approval
    // Roll data will be updated only after Officer approves the entry
    
    // Update the service with all entries
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    console.log('Daily register updated all entries in service:', this.dailyEntries.length, 'entries');
    
    // Close the modal
    const modalElement = document.getElementById('saveConfirmationModal');
    if (modalElement) {
      const modal = (window as any).bootstrap.Modal.getInstance(modalElement);
      if (modal) {
        modal.hide();
      }
    }
    
    // Refresh the display and summary
    this.loadFilteredData();
    this.cdr.detectChanges();
    
    // Clear the entry to save
    this.entryToSave = null;
    
    // Show success message
    alert('✅ Entry saved successfully! Sent to Officer in Charge for verification.');
    
    console.log('Entry saved successfully:', entry);
  }

  /**
   * Save entry to localStorage for Officer in Charge verification
   */
  private saveEntryForOfficerVerification(entry: HologramDailyEntry): void {
    try {
      // Load existing entries from localStorage
      const savedEntries = JSON.parse(localStorage.getItem('dailyRegisterEntries') || '[]');
      
      // Check if entry already exists
      const existingIndex = savedEntries.findIndex((e: any) => e.id === entry.id);
      
      if (existingIndex !== -1) {
        // Update existing entry
        savedEntries[existingIndex] = entry;
      } else {
        // Add new entry
        savedEntries.push(entry);
      }
      
      // Save back to localStorage
      localStorage.setItem('dailyRegisterEntries', JSON.stringify(savedEntries));
      
      console.log('Entry saved for officer verification:', entry.id);
    } catch (error) {
      console.error('Error saving entry for officer verification:', error);
    }
  }

  /**
   * Update roll data in officer-in-charge overview based on saved daily entry
   * Updates Used, Damaged, and Available counts for the corresponding Cartoon Number
   */
  private updateRollData(entry: HologramDailyEntry): void {
    try {
      // Get cartoon number from entry metadata
      const cartoonNumber = (entry as any).cartoonNumber;
      
      if (!cartoonNumber) {
        console.warn('No cartoon number found in entry, skipping roll data update');
        return;
      }
      
      // Load existing roll data from localStorage
      const rollsData = JSON.parse(localStorage.getItem('hologramOverviewRolls') || '[]');
      
      // Find the roll that matches the cartoon number and hologram type
      const rollIndex = rollsData.findIndex((roll: any) => 
        roll.cartoonNumber === cartoonNumber && 
        roll.type === entry.hologramType
      );
      
      if (rollIndex === -1) {
        console.warn(`Roll not found for cartoon number: ${cartoonNumber}, type: ${entry.hologramType}`);
        return;
      }
      
      const roll = rollsData[rollIndex];
      
      // Update the roll counts based on the daily entry
      // Used count increases by issued quantity
      roll.usedCount = (roll.usedCount || 0) + (entry.issuedQuantity || 0);
      
      // Damaged count increases by wastage quantity
      roll.damagedCount = (roll.damagedCount || 0) + (entry.wastageQuantity || 0);
      
      // Available count decreases by total used (issued + wastage)
      const totalUsed = (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0);
      roll.availableCount = Math.max(0, (roll.availableCount || 0) - totalUsed);
      
      // Automatic status update based on available count
      // Logic: If available > 0 → AVAILABLE, If available = 0 → COMPLETED
      if (roll.availableCount === 0) {
        roll.status = 'COMPLETED';
      } else {
        roll.status = 'AVAILABLE';
      }
      
      // Save updated roll data back to localStorage
      rollsData[rollIndex] = roll;
      localStorage.setItem('hologramOverviewRolls', JSON.stringify(rollsData));
      
      // Also update the available hologram data
      this.updateAvailableHologramData(entry, cartoonNumber);
      
      // Also update the serial rolls data
      this.updateSerialRollsData(entry, cartoonNumber);
      
      console.log('Roll data updated successfully:', {
        cartoonNumber,
        type: entry.hologramType,
        usedCount: roll.usedCount,
        damagedCount: roll.damagedCount,
        availableCount: roll.availableCount,
        status: roll.status
      });
      
    } catch (error) {
      console.error('Error updating roll data:', error);
    }
  }

  /**
   * Update available hologram data in officer-in-charge overview
   */
  private updateAvailableHologramData(entry: HologramDailyEntry, cartoonNumber: string): void {
    try {
      const availableData = JSON.parse(localStorage.getItem('hologramOverviewAvailable') || '[]');
      
      const availableIndex = availableData.findIndex((item: any) => 
        item.cartoonNumber === cartoonNumber && 
        item.type === entry.hologramType
      );
      
      if (availableIndex !== -1) {
        const available = availableData[availableIndex];
        
        // Update available count
        const totalUsed = (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0);
        available.availableCount = Math.max(0, (available.availableCount || 0) - totalUsed);
        
        // Update percentage
        const totalCount = available.availableCount + (available.usedCount || 0) + (available.damagedCount || 0);
        available.percentage = totalCount > 0 ? Math.round((available.availableCount / totalCount) * 100) : 0;
        
        // Automatic status update based on available count
        // Logic: If available > 0 → AVAILABLE, If available = 0 → COMPLETED
        if (available.availableCount === 0) {
          available.status = 'COMPLETED';
        } else {
          available.status = 'AVAILABLE';
        }
        
        availableData[availableIndex] = available;
        localStorage.setItem('hologramOverviewAvailable', JSON.stringify(availableData));
        
        console.log('Available hologram data updated:', available);
      }
    } catch (error) {
      console.error('Error updating available hologram data:', error);
    }
  }

  /**
   * Update serial rolls data in officer-in-charge overview
   */
  private updateSerialRollsData(entry: HologramDailyEntry, cartoonNumber: string): void {
    try {
      const serialRollsData = JSON.parse(localStorage.getItem('hologramOverviewSerialData') || '[]');
      
      const serialIndex = serialRollsData.findIndex((roll: any) => 
        roll.rollNumber === cartoonNumber && 
        roll.hologramType === entry.hologramType
      );
      
      if (serialIndex !== -1) {
        const serialRoll = serialRollsData[serialIndex];
        
        // Update counts
        serialRoll.usedCount = (serialRoll.usedCount || 0) + (entry.issuedQuantity || 0);
        serialRoll.damagedCount = (serialRoll.damagedCount || 0) + (entry.wastageQuantity || 0);
        
        const totalUsed = (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0);
        serialRoll.availableCount = Math.max(0, (serialRoll.availableCount || 0) - totalUsed);
        
        // Automatic status update based on available count
        // Logic: If available > 0 → AVAILABLE, If available = 0 → COMPLETED
        if (serialRoll.availableCount === 0) {
          serialRoll.status = 'COMPLETED';
        } else {
          serialRoll.status = 'AVAILABLE';
        }
        
        serialRollsData[serialIndex] = serialRoll;
        localStorage.setItem('hologramOverviewSerialData', JSON.stringify(serialRollsData));
        
        console.log('Serial rolls data updated:', serialRoll);
      }
    } catch (error) {
      console.error('Error updating serial rolls data:', error);
    }
  }



  openMonthlyStatement(): void {
    // Navigate to monthly report with current filters
    this.router.navigate(['/dev-hologram-monthly-report'], {
      queryParams: {
        month: this.selectedMonth,
        year: this.selectedYear,
        type: this.selectedHologramType
      }
    });
  }

  goBack(): void {
    this.router.navigate(['/dev-supply-chain']);
  }

  // Calculate totals for monthly register auto-calculation
  calculateMonthlyTotals(): {
    totalIssued: number;
    totalUtilized: number;
    totalWastage: number;
    totalLeftOver: number;
    utilizationFromSerial: string;
    utilizationToSerial: string;
    wastageFromSerial: string;
    wastageToSerial: string;
  } {
    // Always recalculate from current filtered entries
    const monthEntries = this.filteredEntries.filter(entry => entry.isFixed);
    
    let totalIssued = 0;
    let totalUtilized = 0;
    let totalWastage = 0;
    let totalLeftOver = 0;
    
    let utilizationFromSerial = '';
    let utilizationToSerial = '';
    let wastageFromSerial = '';
    let wastageToSerial = '';

    if (monthEntries.length > 0) {
      // Sort entries by date to get correct first and last serials
      const sortedEntries = monthEntries.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
      
      // Find first and last utilization serials
      const utilizationEntries = sortedEntries.filter(e => e.utilizedQuantity > 0 && e.issuedFromSerial && e.issuedToSerial);
      if (utilizationEntries.length > 0) {
        utilizationFromSerial = utilizationEntries[0].issuedFromSerial || '';
        utilizationToSerial = utilizationEntries[utilizationEntries.length - 1].issuedToSerial || '';
      }

      // Find first and last wastage serials
      const wastageEntries = sortedEntries.filter(e => (e.wastageQuantity || 0) > 0 && e.wastageFromSerial && e.wastageToSerial);
      if (wastageEntries.length > 0) {
        wastageFromSerial = wastageEntries[0].wastageFromSerial || '';
        wastageToSerial = wastageEntries[wastageEntries.length - 1].wastageToSerial || '';
      }

      // Calculate totals
      totalIssued = sortedEntries.reduce((sum, entry) => sum + (entry.issuedQuantity || 0), 0);
      totalUtilized = sortedEntries.reduce((sum, entry) => sum + entry.utilizedQuantity, 0);
      totalWastage = sortedEntries.reduce((sum, entry) => sum + (entry.wastageQuantity || 0), 0);
      totalLeftOver = sortedEntries.reduce((sum, entry) => sum + entry.leftOverQuantity, 0);
    }

    // Update the service with latest totals
    this.hologramDataService.updateDailyEntries(this.dailyEntries);

    return {
      totalIssued,
      totalUtilized,
      totalWastage,
      totalLeftOver,
      utilizationFromSerial,
      utilizationToSerial,
      wastageFromSerial,
      wastageToSerial
    };
  }

  // Force refresh summary
  refreshSummary(): void {
    this.loadFilteredData();
    this.cdr.detectChanges();
  }

  // Get current timestamp for display
  getCurrentTimestamp(): string {
    return new Date().toLocaleString();
  }

  // Check if there are any fixed entries for live data indicator
  hasFixedEntries(): boolean {
    return this.filteredEntries.filter(e => e.isFixed).length > 0;
  }

  // Calculate issued quantity from serials
  calculateIssuedQuantity(entry: HologramDailyEntry): number {
    return this.calculateQuantityFromSerials(entry.issuedFromSerial || '', entry.issuedToSerial || '');
  }

  // Calculate wastage quantity from serials
  calculateWastageQuantity(entry: HologramDailyEntry): number {
    return this.calculateQuantityFromSerials(entry.wastageFromSerial || '', entry.wastageToSerial || '');
  }



  // Load approved hologram entries from officer approvals
  loadApprovedEntries(): void {
    const approvedEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    console.log('Loading approved entries from localStorage:', approvedEntries.length);
    
    // Convert approved entries to daily entry format
    this.approvedEntries = approvedEntries.map((entry: any) => {
      const originalQty = entry.issuedQuantity || entry.utilizedQuantity || 0;
      return {
        id: entry.id,
        date: entry.date,
        hologramType: entry.hologramType,
        issuedFromSerial: entry.issuedFromSerial || '',
        issuedToSerial: entry.issuedToSerial || '',
        issuedQuantity: 0, // Will be calculated from serials
        utilizedQuantity: originalQty,
        wastageFromSerial: entry.wastageFromSerial || '',
        wastageToSerial: entry.wastageToSerial || '',
        wastageQuantity: 0, // Will be calculated from serials
        leftOverQuantity: originalQty, // Will be recalculated
        damageReason: entry.damageReason || '',
        isFixed: entry.isFixed || false,
        // Store original hologram quantity for calculation
        originalHologramQty: originalQty,
        // Additional metadata for display
        referenceNo: entry.referenceNo,
        brandDetails: entry.brandDetails,
        bottleSize: entry.bottleSize,
        submissionDate: entry.submissionDate,
        usageDate: entry.usageDate,
        approvalDate: entry.approvalDate,
        officerName: entry.officerName,
        cartoonNumber: entry.cartoonNumber,
        autoGenerated: entry.autoGenerated || false
      };
    });
  }

  // Merge approved entries with existing entries
  mergeApprovedEntries(existingEntries: HologramDailyEntry[]): void {
    // Get IDs of existing entries to avoid duplicates
    const existingIds = new Set(existingEntries.map(entry => entry.id));
    
    // Filter out approved entries that already exist
    const newApprovedEntries = this.approvedEntries.filter(entry => !existingIds.has(entry.id));
    
    // Combine all entries
    this.dailyEntries = [...existingEntries, ...newApprovedEntries];
    
    // Update the service with merged data
    this.hologramDataService.updateDailyEntries(this.dailyEntries);
    
    console.log('Merged entries:', {
      existing: existingEntries.length,
      newApproved: newApprovedEntries.length,
      total: this.dailyEntries.length
    });
  }

  // Check if entry is auto-generated from approval
  isAutoGenerated(entry: HologramDailyEntry): boolean {
    return (entry as any).autoGenerated === true;
  }

  // Get entry metadata for display
  getEntryMetadata(entry: HologramDailyEntry): any {
    console.log('Entry metadata:', entry);
    return {
      referenceNo: (entry as any).referenceNo || 'Manual Entry',
      brandDetails: (entry as any).brandDetails || { brandName: 'Sample Brand' },
      bottleSize: (entry as any).bottleSize || '750ml',
      submissionDate: (entry as any).submissionDate || entry.date,
      usageDate: (entry as any).usageDate || entry.date,
      approvalDate: (entry as any).approvalDate || entry.date,
      officerName: (entry as any).officerName || 'System',
      cartoonNumber: (entry as any).cartoonNumber || 'CTN001'
    };
  }

  // Manual refresh method
  refreshEntries(): void {
    console.log('Manually refreshing entries...');
    this.loadApprovedEntries();
    this.mergeApprovedEntries(this.hologramDataService.getDailyEntries());
    this.loadFilteredData();
    this.cdr.detectChanges();
    
    const newCount = this.getAutoGeneratedEntriesCount();
    alert(`Entries refreshed! Found ${newCount} auto-generated entries from officer approvals.`);
  }

  // Test method to simulate officer approval
  simulateOfficerApproval(): void {
    const testApprovalEntry = {
      id: `AUTO_${Date.now()}_TEST`,
      date: new Date().toISOString().split('T')[0],
      hologramType: this.selectedHologramType,
      issuedFromSerial: 'HG275346495',
      issuedToSerial: 'HG275347495',
      issuedQuantity: 1000,
      utilizedQuantity: 0,
      wastageFromSerial: '',
      wastageToSerial: '',
      wastageQuantity: 0,
      leftOverQuantity: 1000,
      damageReason: '',
      isFixed: false,
      // Additional metadata for tracking
      referenceNo: `HRQ/${new Date().getFullYear()}/${String(Date.now()).slice(-6)}`,
      brandDetails: {
        brandName: 'Sikkim Supreme Whisky',
        alcoholPercent: '42.8%',
        sizeMl: 750,
        liquorType: 'Whisky'
      },
      bottleSize: '750ml',
      submissionDate: new Date().toISOString().split('T')[0],
      usageDate: new Date().toISOString().split('T')[0],
      approvalDate: new Date().toISOString().split('T')[0],
      officerName: 'Test Officer',
      cartoonNumber: 'CTN001',
      autoGenerated: true
    };

    // Save to localStorage
    const existingEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    existingEntries.push(testApprovalEntry);
    localStorage.setItem('approvedHologramEntries', JSON.stringify(existingEntries));

    // Refresh the display
    this.refreshEntries();
    
    alert('Test officer approval simulated! A new auto-generated entry has been created.');
  }

  // Debug method to check localStorage contents
  debugLocalStorage(): void {
    const approvedEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    const hologramRequests = JSON.parse(localStorage.getItem('hologramRequests') || '[]');
    const hologramApplications = JSON.parse(localStorage.getItem('hologramApplications') || '[]');
    
    console.log('=== LOCALSTORAGE DEBUG ===');
    console.log('approvedHologramEntries:', approvedEntries);
    console.log('hologramRequests:', hologramRequests);
    console.log('hologramApplications:', hologramApplications);
    console.log('Current dailyEntries:', this.dailyEntries);
    console.log('Current filteredEntries:', this.filteredEntries);
    console.log('Current approvedEntries:', this.approvedEntries);
    
    const message = `
LocalStorage Debug:
- approvedHologramEntries: ${approvedEntries.length} items
- hologramRequests: ${hologramRequests.length} items  
- hologramApplications: ${hologramApplications.length} items
- Current dailyEntries: ${this.dailyEntries.length} items
- Current filteredEntries: ${this.filteredEntries.length} items
- Current approvedEntries: ${this.approvedEntries.length} items

Check browser console for detailed data.
    `;
    
    alert(message);
  }

  // Clear all test data
  clearTestData(): void {
    const confirmMessage = 
      `⚠️ WARNING: Clear All Test Data ⚠️\n\n` +
      `This will permanently delete:\n` +
      `• All daily register entries\n` +
      `• All approved hologram entries\n` +
      `• All hologram requests\n` +
      `• All hologram applications\n` +
      `• All localStorage data\n\n` +
      `Current Data:\n` +
      `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n` +
      `• Daily Entries: ${this.dailyEntries.length}\n` +
      `• Filtered Entries: ${this.filteredEntries.length}\n` +
      `• Approved Entries: ${this.approvedEntries.length}\n\n` +
      `This action CANNOT be undone!\n\n` +
      `Are you sure you want to clear all test data?`;
    
    const confirmed = confirm(confirmMessage);
    
    if (!confirmed) {
      console.log('Clear test data cancelled');
      return;
    }
    
    // Double confirmation for safety
    const doubleConfirm = confirm(
      `⚠️ FINAL CONFIRMATION ⚠️\n\n` +
      `This is your last chance to cancel.\n\n` +
      `Click OK to permanently delete all test data.\n` +
      `Click Cancel to keep your data.`
    );
    
    if (!doubleConfirm) {
      console.log('Clear test data cancelled on second confirmation');
      return;
    }
    
    try {
      // Clear localStorage
      localStorage.removeItem('approvedHologramEntries');
      localStorage.removeItem('hologramRequests');
      localStorage.removeItem('hologramApplications');
      localStorage.removeItem('dailyRegisterEntries');
      
      // Clear component data
      this.dailyEntries = [];
      this.filteredEntries = [];
      this.approvedEntries = [];
      
      // Update service
      this.hologramDataService.updateDailyEntries([]);
      
      // Refresh display
      this.loadFilteredData();
      this.cdr.detectChanges();
      
      console.log('All test data cleared successfully');
      
      alert(
        `✅ Test Data Cleared Successfully!\n\n` +
        `All test data has been permanently deleted:\n` +
        `• Daily register entries: Cleared\n` +
        `• Approved entries: Cleared\n` +
        `• Hologram requests: Cleared\n` +
        `• Hologram applications: Cleared\n` +
        `• LocalStorage: Cleared\n\n` +
        `The system is now reset to a clean state.`
      );
    } catch (error) {
      console.error('Error clearing test data:', error);
      alert(
        `❌ Error Clearing Test Data\n\n` +
        `An error occurred while clearing test data.\n` +
        `Please check the console for details.`
      );
    }
  }

  // Pagination methods
  getTotalPages(): number {
    return Math.ceil(this.filteredEntries.length / this.pageSize);
  }

  getPagedEntries(): HologramDailyEntry[] {
    const start = (this.currentPage - 1) * this.pageSize;
    return this.filteredEntries.slice(start, start + this.pageSize);
  }

  goToPage(page: number): void {
    const totalPages = this.getTotalPages();
    if (page >= 1 && page <= totalPages) {
      this.currentPage = page;
    }
  }

  changePageSize(size: number): void {
    this.pageSize = size;
    this.currentPage = 1;
  }

  // Methods for managing multiple issued entries
  addIssuedEntry(entry: HologramDailyEntry): void {
    if (!entry.issuedEntries) {
      entry.issuedEntries = [];
    }
    
    const newIssuedEntry: HologramIssuedEntry = {
      id: this.hologramDataService.generateId(),
      fromSerial: '',
      toSerial: '',
      quantity: 0
    };
    
    entry.issuedEntries.push(newIssuedEntry);
    this.calculateTotalQuantities(entry);
  }

  removeIssuedEntry(entry: HologramDailyEntry, index: number): void {
    if (entry.issuedEntries && entry.issuedEntries.length > 1) {
      entry.issuedEntries.splice(index, 1);
      this.calculateTotalQuantities(entry);
    }
  }

  onIssuedSerialChange(entry: HologramDailyEntry, issuedEntry: HologramIssuedEntry): void {
    // Calculate quantity from serials
    issuedEntry.quantity = this.calculateQuantityFromSerials(issuedEntry.fromSerial, issuedEntry.toSerial);
    console.log('Issued serial changed:', issuedEntry.fromSerial, 'to', issuedEntry.toSerial, '=', issuedEntry.quantity);
    
    // Recalculate total quantities
    this.calculateTotalQuantities(entry);
    
    // DO NOT auto-save - only save when user clicks "Save Entry" button
    // this.hologramDataService.updateDailyEntry(entry);
    
    // Force UI update
    this.cdr.detectChanges();
  }

  // Methods for managing multiple wastage entries
  addWastageEntry(entry: HologramDailyEntry): void {
    if (!entry.wastageEntries) {
      entry.wastageEntries = [];
    }
    
    const newWastageEntry: HologramWastageEntry = {
      id: this.hologramDataService.generateId(),
      fromSerial: '',
      toSerial: '',
      quantity: 0,
      damageReason: ''
    };
    
    entry.wastageEntries.push(newWastageEntry);
    this.calculateTotalQuantities(entry);
  }

  removeWastageEntry(entry: HologramDailyEntry, index: number): void {
    if (entry.wastageEntries && entry.wastageEntries.length > 1) {
      entry.wastageEntries.splice(index, 1);
      this.calculateTotalQuantities(entry);
    }
  }

  onWastageSerialChange(entry: HologramDailyEntry, wastageEntry: HologramWastageEntry): void {
    // Calculate quantity from serials
    wastageEntry.quantity = this.calculateQuantityFromSerials(wastageEntry.fromSerial, wastageEntry.toSerial);
    console.log('Wastage serial changed:', wastageEntry.fromSerial, 'to', wastageEntry.toSerial, '=', wastageEntry.quantity);
    
    // Recalculate total quantities
    this.calculateTotalQuantities(entry);
    
    // DO NOT auto-save - only save when user clicks "Save Entry" button
    // this.hologramDataService.updateDailyEntry(entry);
    
    // Force UI update
    this.cdr.detectChanges();
  }

  // Calculate total quantities from all issued and wastage entries
  calculateTotalQuantities(entry: HologramDailyEntry): void {
    // IMPORTANT: Do NOT recalculate for fixed (saved) entries
    // Once an entry is saved, its quantities should remain exactly as they were
    if (entry.isFixed) {
      console.log('Skipping recalculation for fixed entry:', entry.id);
      return;
    }
    
    // Calculate total issued quantity
    const totalIssued = (entry.issuedEntries || []).reduce((sum, issued) => sum + (issued.quantity || 0), 0);
    
    // Calculate total wastage quantity
    const totalWastage = (entry.wastageEntries || []).reduce((sum, wastage) => sum + (wastage.quantity || 0), 0);
    
    // Update legacy fields for backward compatibility
    entry.issuedQuantity = totalIssued;
    entry.wastageQuantity = totalWastage;
    
    // Get original hologram quantity
    const originalHologramQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
    
    // Calculate left over: Original Hologram Qty - (Issued Qty + Wastage Qty)
    const totalUsed = totalIssued + totalWastage;
    entry.leftOverQuantity = originalHologramQty - totalUsed;
    
    // Validate that total used doesn't exceed hologram quantity
    if (totalUsed > originalHologramQty) {
      (entry as any).hasValidationError = true;
      (entry as any).validationMessage = `Total usage exceeds available quantity`;
    } else {
      (entry as any).hasValidationError = false;
      (entry as any).validationMessage = '';
    }
  }

  // Get total issued quantity for display
  getTotalIssuedQuantity(entry: HologramDailyEntry): number {
    return this.hologramDataService.getTotalIssuedQuantity(entry);
  }

  // Get total wastage quantity for display
  getTotalWastageQuantity(entry: HologramDailyEntry): number {
    return this.hologramDataService.getTotalWastageQuantity(entry);
  }

  // Initialize entries with at least one issued and wastage entry
  initializeEntryArrays(entry: HologramDailyEntry): void {
    if (!entry.issuedEntries || entry.issuedEntries.length === 0) {
      entry.issuedEntries = [{
        id: this.hologramDataService.generateId(),
        fromSerial: entry.issuedFromSerial || '',
        toSerial: entry.issuedToSerial || '',
        quantity: entry.issuedQuantity || 0
      }];
    }
    
    if (!entry.wastageEntries || entry.wastageEntries.length === 0) {
      entry.wastageEntries = [{
        id: this.hologramDataService.generateId(),
        fromSerial: entry.wastageFromSerial || '',
        toSerial: entry.wastageToSerial || '',
        quantity: entry.wastageQuantity || 0,
        damageReason: entry.damageReason || ''
      }];
    }
  }

  // Get validation status for an entry
  hasValidationError(entry: HologramDailyEntry): boolean {
    return entry.leftOverQuantity < 0;
  }

  // Get validation message for display
  getValidationMessage(entry: HologramDailyEntry): string {
    if (entry.leftOverQuantity < 0) {
      const originalQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
      const totalUsed = (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0);
      const excess = totalUsed - originalQty;
      return `Exceeds available quantity by ${excess.toLocaleString()} units`;
    }
    return '';
  }

  // Check if calculation matches hologram quantity
  isCalculationMatching(entry: HologramDailyEntry): boolean {
    const originalQty = (entry as any).originalHologramQty || entry.utilizedQuantity;
    const totalCalculated = (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0) + entry.leftOverQuantity;
    return originalQty === totalCalculated;
  }

  // Get total calculation (Issued + Wastage + Left Over)
  getTotalCalculation(entry: HologramDailyEntry): number {
    return (entry.issuedQuantity || 0) + (entry.wastageQuantity || 0) + entry.leftOverQuantity;
  }

  /**
   * Test method to verify roll data update functionality
   * This method helps test if the roll data is being updated correctly
   */
  testRollDataUpdate(): void {
    const cartoonNumber = prompt('Enter Cartoon Number to verify (e.g., cttest1):');
    
    if (!cartoonNumber) {
      alert('Test cancelled - no cartoon number provided');
      return;
    }
    
    try {
      // Load roll data from localStorage
      const rollsData = JSON.parse(localStorage.getItem('hologramOverviewRolls') || '[]');
      const availableData = JSON.parse(localStorage.getItem('hologramOverviewAvailable') || '[]');
      const serialData = JSON.parse(localStorage.getItem('hologramOverviewSerialData') || '[]');
      
      // Find the roll
      const roll = rollsData.find((r: any) => r.cartoonNumber === cartoonNumber);
      const available = availableData.find((a: any) => a.cartoonNumber === cartoonNumber);
      const serial = serialData.find((s: any) => s.rollNumber === cartoonNumber);
      
      if (!roll) {
        alert(`❌ Roll not found: ${cartoonNumber}\n\nAvailable rolls:\n${rollsData.map((r: any) => r.cartoonNumber).join(', ')}`);
        return;
      }
      
      // Display current roll data
      const message = `
🔍 ROLL DATA VERIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📦 Cartoon Number: ${roll.cartoonNumber}
🏷️  Type: ${roll.type}

📊 CURRENT COUNTS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Count: ${roll.totalCount}
Available: ${roll.availableCount}
Used: ${roll.usedCount}
Damaged: ${roll.damagedCount}
Status: ${roll.status}

✅ DATA CONSISTENCY CHECK:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Rolls Tab: Available=${roll.availableCount}, Used=${roll.usedCount}, Damaged=${roll.damagedCount}
Available Tab: ${available ? `Available=${available.availableCount}, Status=${available.status}` : 'Not found'}
Serial Tab: ${serial ? `Available=${serial.availableCount}, Used=${serial.usedCount}, Damaged=${serial.damagedCount}` : 'Not found'}

📝 CALCULATION VERIFICATION:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total = Available + Used + Damaged
${roll.totalCount} = ${roll.availableCount} + ${roll.usedCount} + ${roll.damagedCount}
${roll.totalCount} = ${roll.availableCount + roll.usedCount + roll.damagedCount}
${roll.totalCount === (roll.availableCount + roll.usedCount + roll.damagedCount) ? '✅ CORRECT' : '❌ MISMATCH'}

🎯 STATUS LOGIC:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Current Status: ${roll.status}
Expected Status: ${roll.availableCount === 0 ? 'COMPLETED' : 'AVAILABLE'}
${roll.status === (roll.availableCount === 0 ? 'COMPLETED' : 'AVAILABLE') ? '✅ CORRECT' : '❌ INCORRECT'}

💡 NEXT STEPS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Save a daily entry for this roll
2. Run this test again to verify updates
3. Check that counts change correctly
4. Verify status updates automatically
      `;
      
      console.log(message);
      alert(message);
      
      // Also log to console for detailed inspection
      console.log('=== DETAILED ROLL DATA ===');
      console.log('Roll:', roll);
      console.log('Available:', available);
      console.log('Serial:', serial);
      
    } catch (error) {
      console.error('Error testing roll data:', error);
      alert(`❌ Error testing roll data:\n${error}`);
    }
  }

  /**
   * Quick test to create a test roll for testing
   */
  createTestRoll(): void {
    const cartoonNumber = prompt('Enter Cartoon Number for test roll (e.g., TEST001):');
    
    if (!cartoonNumber) {
      alert('Test cancelled');
      return;
    }
    
    const totalCount = parseInt(prompt('Enter Total Count (e.g., 1000):', '1000') || '1000');
    
    const testRoll = {
      id: Date.now(),
      cartoonNumber: cartoonNumber,
      type: this.selectedHologramType,
      fromSerial: 'HG001001',
      toSerial: `HG${String(1000 + totalCount).padStart(6, '0')}`,
      totalCount: totalCount,
      availableCount: totalCount,
      usedCount: 0,
      damagedCount: 0,
      status: 'AVAILABLE',
      receivedDate: new Date().toISOString().split('T')[0],
      isNew: true,
      newUntil: Date.now() + (24 * 60 * 60 * 1000) // 24 hours
    };
    
    // Add to all three data sources
    const rollsData = JSON.parse(localStorage.getItem('hologramOverviewRolls') || '[]');
    rollsData.unshift(testRoll); // Add at beginning
    localStorage.setItem('hologramOverviewRolls', JSON.stringify(rollsData));
    
    const availableData = JSON.parse(localStorage.getItem('hologramOverviewAvailable') || '[]');
    availableData.unshift({
      id: testRoll.id,
      cartoonNumber: testRoll.cartoonNumber,
      type: testRoll.type,
      availableRange: `${testRoll.fromSerial} - ${testRoll.toSerial}`,
      availableCount: testRoll.availableCount,
      nextSerial: testRoll.fromSerial,
      percentage: 100,
      status: 'AVAILABLE',
      isNew: true,
      newUntil: testRoll.newUntil
    });
    localStorage.setItem('hologramOverviewAvailable', JSON.stringify(availableData));
    
    const serialData = JSON.parse(localStorage.getItem('hologramOverviewSerialData') || '[]');
    serialData.unshift({
      id: testRoll.id,
      rollNumber: testRoll.cartoonNumber,
      hologramType: testRoll.type,
      fromSerial: testRoll.fromSerial,
      toSerial: testRoll.toSerial,
      totalCount: testRoll.totalCount,
      availableCount: testRoll.availableCount,
      usedCount: 0,
      damagedCount: 0,
      status: 'AVAILABLE',
      receivedDate: testRoll.receivedDate,
      usageHistory: [],
      isNew: true,
      newUntil: testRoll.newUntil
    });
    localStorage.setItem('hologramOverviewSerialData', JSON.stringify(serialData));
    
    // Create a test entry in daily register
    const testEntry = {
      id: `TEST_${Date.now()}`,
      date: new Date().toISOString().split('T')[0],
      hologramType: this.selectedHologramType,
      issuedFromSerial: '',
      issuedToSerial: '',
      issuedQuantity: 0,
      utilizedQuantity: totalCount,
      wastageFromSerial: '',
      wastageToSerial: '',
      wastageQuantity: 0,
      leftOverQuantity: totalCount,
      damageReason: '',
      isFixed: false,
      referenceNo: `TEST/${new Date().getFullYear()}/${String(Date.now()).slice(-6)}`,
      brandDetails: {
        brandName: 'Test Brand',
        alcoholPercent: '40%',
        sizeMl: 750,
        liquorType: 'Test'
      },
      bottleSize: '750ml',
      submissionDate: new Date().toISOString().split('T')[0],
      usageDate: new Date().toISOString().split('T')[0],
      approvalDate: new Date().toISOString().split('T')[0],
      officerName: 'Test Officer',
      cartoonNumber: cartoonNumber,
      autoGenerated: true,
      originalHologramQty: totalCount
    };
    
    // Add to approved entries
    const approvedEntries = JSON.parse(localStorage.getItem('approvedHologramEntries') || '[]');
    approvedEntries.push(testEntry);
    localStorage.setItem('approvedHologramEntries', JSON.stringify(approvedEntries));
    
    alert(`✅ Test roll created successfully!\n\nCartoon Number: ${cartoonNumber}\nType: ${this.selectedHologramType}\nTotal Count: ${totalCount}\n\nRefresh the page to see the new roll.`);
    
    // Refresh entries
    this.refreshEntries();
  }

  /**
   * Get unique entries (group by reference number to avoid duplicates)
   */
  getUniquePagedEntries(): HologramDailyEntry[] {
    const pagedEntries = this.getPagedEntries();
    const uniqueMap = new Map<string, HologramDailyEntry>();
    
    pagedEntries.forEach(entry => {
      const refNo = this.getEntryMetadata(entry).referenceNo;
      if (!uniqueMap.has(refNo)) {
        uniqueMap.set(refNo, entry);
      }
    });
    
    return Array.from(uniqueMap.values());
  }

  /**
   * Get all rolls assigned to an entry (by reference number)
   */
  getAssignedRolls(entry: HologramDailyEntry): string[] {
    const refNo = this.getEntryMetadata(entry).referenceNo;
    const allEntriesWithSameRef = this.filteredEntries.filter(e => 
      this.getEntryMetadata(e).referenceNo === refNo
    );
    
    const rolls = allEntriesWithSameRef.map(e => {
      const cartoonNumber = (e as any).cartoonNumber || this.getEntryMetadata(e).cartoonNumber;
      return cartoonNumber;
    }).filter(roll => roll); // Remove empty values
    
    // Return unique rolls
    return [...new Set(rolls)];
  }

  /**
   * Get available rolls for an entry (from the assigned rolls for that entry)
   */
  getAvailableRollsForEntry(entry: HologramDailyEntry): any[] {
    // Get all rolls assigned to this entry
    const assignedRolls = this.getAssignedRolls(entry);
    
    // Load roll details from localStorage (officer's allocation)
    const allocatedRolls = JSON.parse(localStorage.getItem('hologramAllocations') || '[]');
    
    // Return roll details for assigned rolls
    return assignedRolls.map(cartoonNumber => {
      const rollDetail = allocatedRolls.find((r: any) => r.cartoonNumber === cartoonNumber);
      return rollDetail || {
        cartoonNumber: cartoonNumber,
        availableCount: 1000, // Default
        serialRange: '000001-001000',
        remainingInCartoon: 1000
      };
    });
  }

  /**
   * Get current selected roll for entry
   */
  getCurrentSelectedRoll(entry: HologramDailyEntry): string | null {
    const rollData = (entry as any).currentRollSelection;
    return rollData?.selectedRoll || null;
  }

  /**
   * Get current roll input data
   */
  getCurrentRollInput(entry: HologramDailyEntry): any {
    return (entry as any).currentRollSelection?.rollInput;
  }

  /**
   * Check if roll input is locked
   */
  isRollInputLocked(entry: HologramDailyEntry): boolean {
    return (entry as any).currentRollSelection?.isLocked || false;
  }

  /**
   * Get locked rolls for entry
   */
  getLockedRollsForEntry(entry: HologramDailyEntry): any[] {
    return (entry as any).lockedRolls || [];
  }

  /**
   * Select a roll for entry
   */
  selectRollForEntry(entry: HologramDailyEntry, cartoonNumber: string): void {
    if (!cartoonNumber) return;

    // Find the roll details
    const roll = this.getAvailableRollsForEntry(entry).find(r => r.cartoonNumber === cartoonNumber);
    if (!roll) return;

    // Check if already locked
    const lockedRolls = this.getLockedRollsForEntry(entry);
    if (lockedRolls.some((lr: any) => lr.cartoonNumber === cartoonNumber)) {
      alert('This roll is already locked.');
      return;
    }

    // Initialize roll selection data
    (entry as any).currentRollSelection = {
      selectedRoll: cartoonNumber,
      rollInput: {
        cartoonNumber: cartoonNumber,
        availableCount: roll.remainingInCartoon || roll.availableCount || 1000,
        serialRange: roll.serialRange,
        issuedFrom: '',
        issuedTo: '',
        issuedQty: 0,
        wastageFrom: '',
        wastageTo: '',
        wastageQty: 0,
        leftOver: roll.remainingInCartoon || roll.availableCount || 1000
      },
      isLocked: false
    };

    this.cdr.detectChanges();
  }

  /**
   * Handle roll input changes
   */
  onRollInputChange(entry: HologramDailyEntry): void {
    const rollInput = this.getCurrentRollInput(entry);
    if (!rollInput) return;

    // Calculate issued quantity
    rollInput.issuedQty = this.calculateQuantityFromSerials(
      rollInput.issuedFrom,
      rollInput.issuedTo
    );

    // Calculate wastage quantity
    rollInput.wastageQty = this.calculateQuantityFromSerials(
      rollInput.wastageFrom,
      rollInput.wastageTo
    );

    // Calculate left over
    const totalUsed = rollInput.issuedQty + rollInput.wastageQty;
    rollInput.leftOver = rollInput.availableCount - totalUsed;

    this.cdr.detectChanges();
  }

  /**
   * Check if roll can be locked
   */
  canLockRoll(entry: HologramDailyEntry): boolean {
    const rollInput = this.getCurrentRollInput(entry);
    if (!rollInput) return false;

    // Must have issued serials
    if (!rollInput.issuedFrom || !rollInput.issuedTo) return false;

    // Left over must not be negative
    if (rollInput.leftOver < 0) return false;

    return true;
  }

  /**
   * Lock the current roll
   */
  lockRollForEntry(entry: HologramDailyEntry): void {
    const rollInput = this.getCurrentRollInput(entry);
    if (!rollInput || !this.canLockRoll(entry)) {
      alert('Please enter valid serial numbers before locking.');
      return;
    }

    // Initialize locked rolls array
    if (!(entry as any).lockedRolls) {
      (entry as any).lockedRolls = [];
    }

    // Add to locked rolls
    (entry as any).lockedRolls.push({ ...rollInput });

    // Clear current selection
    (entry as any).currentRollSelection = null;

    // Recalculate entry totals
    this.recalculateEntryFromLockedRolls(entry);

    alert(`Roll ${rollInput.cartoonNumber} locked successfully! You can now select another roll or save the entry.`);
    this.cdr.detectChanges();
  }

  /**
   * Unlock a roll
   */
  unlockRollForEntry(entry: HologramDailyEntry, cartoonNumber: string): void {
    const lockedRolls = (entry as any).lockedRolls || [];
    const index = lockedRolls.findIndex((r: any) => r.cartoonNumber === cartoonNumber);

    if (index !== -1) {
      lockedRolls.splice(index, 1);
      this.recalculateEntryFromLockedRolls(entry);
      this.cdr.detectChanges();
    }
  }

  /**
   * Recalculate entry totals from locked rolls
   */
  recalculateEntryFromLockedRolls(entry: HologramDailyEntry): void {
    const lockedRolls = (entry as any).lockedRolls || [];

    let totalIssued = 0;
    let totalWastage = 0;
    let totalLeftOver = 0;

    lockedRolls.forEach((roll: any) => {
      totalIssued += roll.issuedQty || 0;
      totalWastage += roll.wastageQty || 0;
      totalLeftOver += roll.leftOver || 0;
    });

    entry.issuedQuantity = totalIssued;
    entry.wastageQuantity = totalWastage;
    entry.leftOverQuantity = totalLeftOver;

    // Update issued and wastage entries arrays
    entry.issuedEntries = lockedRolls
      .filter((roll: any) => roll.issuedQty > 0)
      .map((roll: any) => ({
        id: this.hologramDataService.generateId(),
        fromSerial: roll.issuedFrom,
        toSerial: roll.issuedTo,
        quantity: roll.issuedQty
      }));

    entry.wastageEntries = lockedRolls
      .filter((roll: any) => roll.wastageQty > 0)
      .map((roll: any) => ({
        id: this.hologramDataService.generateId(),
        fromSerial: roll.wastageFrom,
        toSerial: roll.wastageTo,
        quantity: roll.wastageQty,
        damageReason: entry.damageReason || ''
      }));
  }

  /**
   * Check if entry has locked rolls
   */
  hasLockedRolls(entry: HologramDailyEntry): boolean {
    const lockedRolls = (entry as any).lockedRolls || [];
    return lockedRolls.length > 0;
  }
}
